-- Script de Creación de la Base de Datos

-- Claves foráneas
PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS TIPO_ARTE;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS LOCAL;
DROP TABLE IF EXISTS GALERIA;
DROP TABLE IF EXISTS COMUNA;
DROP TABLE IF EXISTS REGION;

-- Tabla REGION
CREATE TABLE REGION (
    id_reg INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL
);


-- Tabla COMUNA

CREATE TABLE COMUNA (
    id_com INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    id_reg INTEGER NOT NULL,
    FOREIGN KEY (id_reg) REFERENCES REGION(id_reg)
);


-- Tabla GALERIA

CREATE TABLE GALERIA (
    id_galeria INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    direccion TEXT NOT NULL,
    id_com INTEGER NOT NULL,
    FOREIGN KEY (id_com) REFERENCES COMUNA(id_com)
);


-- Tabla LOCAL

CREATE TABLE LOCAL (
    id_local INTEGER PRIMARY KEY AUTOINCREMENT,
    num_local INTEGER NOT NULL,
    direccion TEXT NOT NULL,
    id_galeria INTEGER NOT NULL,
    id_com INTEGER NOT NULL,
    FOREIGN KEY (id_galeria) REFERENCES GALERIA(id_galeria),
    FOREIGN KEY (id_com) REFERENCES COMUNA(id_com)
);


-- Tabla EMPLEADO

CREATE TABLE EMPLEADO (
    id_emp INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    sueldo INTEGER NOT NULL,
    genero TEXT NOT NULL CHECK (genero IN ('M', 'F', 'O')),
    cargo TEXT NOT NULL,
    id_galeria INTEGER NOT NULL,
    FOREIGN KEY (id_galeria) REFERENCES GALERIA(id_galeria)
);


-- Tabla TIPO_ARTE

CREATE TABLE TIPO_ARTE (
    id_tipo INTEGER PRIMARY KEY AUTOINCREMENT,
    descripcion TEXT NOT NULL
);


-- Tabla PRODUCTO

CREATE TABLE PRODUCTO (
    id_prod INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    precio INTEGER NOT NULL,
    peso REAL NOT NULL,
    id_tipo INTEGER NOT NULL,
    id_local INTEGER NOT NULL,
    FOREIGN KEY (id_tipo) REFERENCES TIPO_ARTE(id_tipo),
    FOREIGN KEY (id_local) REFERENCES LOCAL(id_local)
);


-- Tabla CLIENTE

CREATE TABLE CLIENTE (
    id_cli INTEGER PRIMARY KEY AUTOINCREMENT,
    rut TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL
);


-- Tabla VENTA

CREATE TABLE VENTA (
    id_venta INTEGER PRIMARY KEY AUTOINCREMENT,
    fecha TEXT NOT NULL, 
    monto INTEGER NOT NULL,
    id_emp INTEGER NOT NULL,
    id_cli INTEGER NOT NULL,
    id_prod INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (id_emp) REFERENCES EMPLEADO(id_emp),
    FOREIGN KEY (id_cli) REFERENCES CLIENTE(id_cli),
    FOREIGN KEY (id_prod) REFERENCES PRODUCTO(id_prod)
);


